# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER
jobs:
   build:
     docker:
       - image: circleci/node:latest
test:
  override:    
    - mocha